//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Verb.java
//

#ifndef _Verb_H_
#define _Verb_H_

@class IOSCharArray;
@class IOSIntArray;
@class IOSObjectArray;

#include "J2ObjC_header.h"

#define Verb_AO YES
#define Verb_BR 0
#define Verb_COMPOUND_PAST_PERFECT 15
#define Verb_CONDITIONAL 5
#define Verb_CONDITIONAL_PERFECT 17
#define Verb_FUTURE_INDICATIVE 4
#define Verb_FUTURE_PERFECT 16
#define Verb_FUTURE_PERFECT_SUBJ 20
#define Verb_FUTURE_SUBJUNCTIVE 8
#define Verb_GERUND 12
#define Verb_IMPERATIVE_AFF 10
#define Verb_IMPERATIVE_NEG 11
#define Verb_IMPERFECT_SUBJUNCTIVE 7
#define Verb_PAST_PARTICIPLE 13
#define Verb_PAST_PERFECT_SUBJ 19
#define Verb_PERSONAL_INFINITIVE 9
#define Verb_PLUPERFECT_INDICATIVE 3
#define Verb_PRESENT_INDICATIVE 0
#define Verb_PRESENT_PERFECT 14
#define Verb_PRESENT_PERFECT_SUBJ 18
#define Verb_PRESENT_SUBJUNCTIVE 6
#define Verb_PRETERITE_IMPERFECT 1
#define Verb_PRETERITE_PERFECT 2
#define Verb_PT 1
#define Verb_aAcute 0x00e1
#define Verb_aAcuteUp 0x00c1
#define Verb_aGrave 0x00e0
#define Verb_aGraveUp 0x00c0
#define Verb_aTilde 0x00e3
#define Verb_aTildeUp 0x00c3
#define Verb_cCedil 0x00e7
#define Verb_cCedilUp 0x00c7
#define Verb_eAcute 0x00e9
#define Verb_eAcuteUp 0x00c9
#define Verb_eCFlex 0x00ea
#define Verb_eCFlexUp 0x00ca
#define Verb_emDash 0x2014
#define Verb_enDash 0x2013
#define Verb_figDash 0x2012
#define Verb_hyphen 0x2010
#define Verb_iAcute 0x00ed
#define Verb_iAcuteUp 0x00cd
#define Verb_minus '-'
#define Verb_nbHyphen 0x2011
#define Verb_oAcute 0x00f3
#define Verb_oAcuteUp 0x00d3
#define Verb_oCFlex 0x00f4
#define Verb_oCFlexUp 0x00d4
#define Verb_oTilde 0x00f5
#define Verb_oTildeUp 0x00d5
#define Verb_uAcute 0x00fa
#define Verb_uAcuteUp 0x00da
#define Verb_uTreme 0x00fc
#define Verb_uTremeUp 0x00dc

@interface Verb : NSObject {
}

+ (void)resetTables;

- (instancetype)initWithNSString:(NSString *)infinitive;

+ (jboolean)hasValidEndingWithNSString:(NSString *)s;

+ (jboolean)isValidCharWithChar:(jchar)c;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

@end

FOUNDATION_EXPORT BOOL Verb_initialized;
J2OBJC_STATIC_INIT(Verb)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT void Verb_resetTables();

FOUNDATION_EXPORT jboolean Verb_hasValidEndingWithNSString_(NSString *s);

FOUNDATION_EXPORT jboolean Verb_isValidCharWithChar_(jchar c);

FOUNDATION_EXPORT void Verb_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_STATIC_FIELD_GETTER(Verb, BR, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PT, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, AO, jboolean)

J2OBJC_STATIC_FIELD_GETTER(Verb, PRESENT_INDICATIVE, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PRETERITE_IMPERFECT, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PRETERITE_PERFECT, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PLUPERFECT_INDICATIVE, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, FUTURE_INDICATIVE, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, CONDITIONAL, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PRESENT_SUBJUNCTIVE, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, IMPERFECT_SUBJUNCTIVE, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, FUTURE_SUBJUNCTIVE, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PERSONAL_INFINITIVE, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, IMPERATIVE_AFF, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, IMPERATIVE_NEG, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, GERUND, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PAST_PARTICIPLE, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PRESENT_PERFECT, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, COMPOUND_PAST_PERFECT, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, FUTURE_PERFECT, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, CONDITIONAL_PERFECT, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PRESENT_PERFECT_SUBJ, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, PAST_PERFECT_SUBJ, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, FUTURE_PERFECT_SUBJ, jint)

J2OBJC_STATIC_FIELD_GETTER(Verb, aAcuteUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, aAcute, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, aGraveUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, aGrave, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, aTildeUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, aTilde, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, cCedilUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, cCedil, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, eAcuteUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, eAcute, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, eCFlexUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, eCFlex, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, iAcuteUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, iAcute, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, oAcuteUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, oAcute, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, oCFlexUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, oCFlex, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, oTildeUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, oTilde, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, uAcuteUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, uAcute, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, uTremeUp, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, uTreme, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, minus, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, hyphen, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, nbHyphen, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, figDash, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, enDash, jchar)

J2OBJC_STATIC_FIELD_GETTER(Verb, emDash, jchar)

FOUNDATION_EXPORT IOSCharArray *Verb_accents_;
J2OBJC_STATIC_FIELD_GETTER(Verb, accents_, IOSCharArray *)

FOUNDATION_EXPORT IOSCharArray *Verb_dashes_;
J2OBJC_STATIC_FIELD_GETTER(Verb, dashes_, IOSCharArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_darDerivs_;
J2OBJC_STATIC_FIELD_GETTER(Verb, darDerivs_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_estarDerivs_;
J2OBJC_STATIC_FIELD_GETTER(Verb, estarDerivs_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_lerDerivs_;
J2OBJC_STATIC_FIELD_GETTER(Verb, lerDerivs_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_terDerivs_;
J2OBJC_STATIC_FIELD_GETTER(Verb, terDerivs_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_verDerivs_;
J2OBJC_STATIC_FIELD_GETTER(Verb, verDerivs_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_virDerivs_;
J2OBJC_STATIC_FIELD_GETTER(Verb, virDerivs_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_thPerSing_;
J2OBJC_STATIC_FIELD_GETTER(Verb, thPerSing_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_thPerBoth_;
J2OBJC_STATIC_FIELD_GETTER(Verb, thPerBoth_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_onlyArriz_;
J2OBJC_STATIC_FIELD_GETTER(Verb, onlyArriz_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_noFstPerSing_;
J2OBJC_STATIC_FIELD_GETTER(Verb, noFstPerSing_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_brConjComAO_;
J2OBJC_STATIC_FIELD_GETTER(Verb, brConjComAO_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(Verb, brConjComAO_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_brConjSemAO_;
J2OBJC_STATIC_FIELD_GETTER(Verb, brConjSemAO_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(Verb, brConjSemAO_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_ptConjComAO_;
J2OBJC_STATIC_FIELD_GETTER(Verb, ptConjComAO_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(Verb, ptConjComAO_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_ptConjSemAO_;
J2OBJC_STATIC_FIELD_GETTER(Verb, ptConjSemAO_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(Verb, ptConjSemAO_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_ends_;
J2OBJC_STATIC_FIELD_GETTER(Verb, ends_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(Verb, ends_, IOSObjectArray *)

FOUNDATION_EXPORT IOSIntArray *Verb_stems_;
J2OBJC_STATIC_FIELD_GETTER(Verb, stems_, IOSIntArray *)
J2OBJC_STATIC_FIELD_SETTER(Verb, stems_, IOSIntArray *)

FOUNDATION_EXPORT NSString *Verb_stem_;
J2OBJC_STATIC_FIELD_GETTER(Verb, stem_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(Verb, stem_, NSString *)

FOUNDATION_EXPORT NSString *Verb_stem2_;
J2OBJC_STATIC_FIELD_GETTER(Verb, stem2_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(Verb, stem2_, NSString *)

FOUNDATION_EXPORT NSString *Verb_stem3_;
J2OBJC_STATIC_FIELD_GETTER(Verb, stem3_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(Verb, stem3_, NSString *)

FOUNDATION_EXPORT NSString *Verb_stem4_;
J2OBJC_STATIC_FIELD_GETTER(Verb, stem4_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(Verb, stem4_, NSString *)

FOUNDATION_EXPORT IOSObjectArray *Verb_estarTable_;
J2OBJC_STATIC_FIELD_GETTER(Verb, estarTable_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_haverTable_;
J2OBJC_STATIC_FIELD_GETTER(Verb, haverTable_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_serTable_;
J2OBJC_STATIC_FIELD_GETTER(Verb, serTable_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *Verb_terTable_;
J2OBJC_STATIC_FIELD_GETTER(Verb, terTable_, IOSObjectArray *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(Verb)

#endif // _Verb_H_
